name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Node.js installieren
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Tests ausführen
        run: npx vitest run
